default_agent: evaluation_agent_02
agents:
  evaluation_agent_02:
    name: evaluation_agent_02
    language: python
    node_version: '20'
    entrypoint: D:/FPT/AWS/agentcore-testing/agentcore-evaluation/evaluation_02/agent.py
    deployment_type: container
    runtime_type: null
    platform: linux/arm64
    container_runtime: docker
    source_path: D:\FPT\AWS\agentcore-testing\agentcore-evaluation\evaluation_02
    aws:
      execution_role: arn:aws:iam::381492273521:role/AgentRuntimeRole
      execution_role_auto_create: true
      account: '381492273521'
      region: us-west-2
      ecr_repository: 381492273521.dkr.ecr.us-west-2.amazonaws.com/evaluation-agent-02
      ecr_auto_create: false
      s3_path: null
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: evaluation_agent_02-ToChVoCQ4o
      agent_arn: arn:aws:bedrock-agentcore:us-west-2:381492273521:runtime/evaluation_agent_02-ToChVoCQ4o
      agent_session_id: 0d6c5629-9bc0-4b83-ab8b-70473c691564
    codebuild:
      project_name: bedrock-agentcore-evaluation_agent_02-builder
      execution_role: arn:aws:iam::381492273521:role/AmazonBedrockAgentCoreSDKCodeBuild-us-west-2-2e01738643
      source_bucket: bedrock-agentcore-codebuild-sources-381492273521-us-west-2
    memory:
      mode: NO_MEMORY
      memory_id: null
      memory_arn: null
      memory_name: null
      event_expiry_days: 30
      first_invoke_memory_check_done: false
      was_created_by_toolkit: false
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: false
